name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: install dependencies
      run: pnpm install
    - name: lint
      run: pnpm lint

  legacy-node-test:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ['6', '8', '10', '12', '14', '16', '18']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: cat <<< $(jq '.packageManager = "yarn@1.22.22"' package.json) > package.json
    - name: install dependencies
      run: yarn install --frozen-lockfile --ignore-engines
    - name: test
      run: yarn test

  test:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ['20', '22', '24']

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: pnpm
    - name: install dependencies
      run: pnpm install
    - name: test
      run: pnpm run test

  floating-test:
    name: Floating dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: install dependencies
      run: pnpm install --no-lockfile
    - name: test
      run: pnpm test
